const basic = [
  {
    name: 'Juno',
    age: 11,
    color: 'black & tan',
    weight: 65,
    breed: 'Husky Mix',
    sex: F,
  },
  {
    name: 'Poppy',
    age: 6,
    color: 'fawn',
    weight: 25,
    breed: 'French Bulldog',
    sex: F,
  },

  {
    name: 'Wuffles',
    age: 12,
    color: 'black',
    weight: 18,
    breed: 'Shih Tzu',
    sex: M,
  },
  {
    name: 'Mr. Fusspot',
    age: 9,
    color: 'brown',
    weight: 9,
    breed: 'Toy Poodle',
    sex: M,
  },
  {
    name: 'Laddie',
    age: 6,
    color: 'red',
    weight: 40,
    breed: 'Border Collie',
    sex: M,
  },
  {
    name: 'Agusta',
    age: 4,
    color: 'white',
    weight: 54,
    breed: 'Golden Retriever',
    sex: F,
  },
  {
    name: 'Rincewind',
    age: 3,
    color: 'black',
    weight: 8,
    breed: 'Chihuahua',
    sex: M,
  },
  {
    name: 'Weatherwax',
    age: 12,
    color: 'brown',
    weight: 13,
    breed: 'Doberman Pinscher',
    sex: M,
  },
  {
    name: 'Magrat',
    age: 5,
    color: 'red',
    weight: 60,
    breed: 'Standard Poodle',
    sex: F,
  },
  {
    name: 'Greebo',
    age: 2,
    color: 'black',
    weight: 44,
    breed: 'Rottweiler',
    sex: M,
  },
  {
    name: 'Stibbons',
    age: 7,
    color: 'black',
    weight: 6,
    breed: 'Yorkshire Terrier',
    sex: F,
  },
  {
    name: 'Vetinari',
    age: 5,
    color: 'black',
    weight: 20,
    breed: 'Schipperke',
    sex: M,
  },
  {
    name: 'Motzart',
    age: 4,
    color: 'red',
    weight: 135,
    breed: 'Saint Bernard',
    sex: M,
  },
  {
    name: 'The Librarian',
    age: 8,
    color: 'red',
    weight: 40,
    breed: 'Basset Hound',
    sex: F,
  },
  {
    name: 'TwoFlower',
    age: 3,
    color: 'brown',
    weight: 52,
    breed: 'Chow Chow',
    sex: F,
  },
  {
    name: 'Detritus',
    age: 4,
    color: 'white',
    weight: 84,
    breed: 'Mastiff',
    sex: M,
  },
  {
    name: 'Carrot',
    age: 10,
    color: 'red',
    weight: 61,
    breed: 'Golden Retriever',
    sex: F,
  },
  {
    name: 'Vimes',
    age: 3,
    color: 'brown',
    weight: 38,
    breed: 'English Bulldog',
    sex: M,
  },
  {
    name: 'Cherry',
    age: 13,
    color: 'brown',
    weight: 31,
    breed: 'Shetland Sheepdog',
    sex: F,
  },
  {
    name: 'Nobby',
    age: 9,
    color: 'brown',
    weight: 19,
    breed: 'Pug',
    sex: M,
  },
  {
    name: 'Brutha',
    age: 6,
    color: 'white',
    weight: 21,
    breed: 'Pembroke Welsh Corgi',
    sex: M,
  },
  {
    name: 'Puddles',
    color: 'Black and white',
    age: 11,
    weight: 65,
    breed: 'Beagle Mix',
    sex: F,
  },
  {
    name: 'Sandy',
    color: 'tan',
    age: 6,
    weight: 69,
    breed: 'American Bulldog',
    sex: F,
  },

  {
    name: 'Fluffles',
    age: 1,
    color: 'grey',
    weight: 88,
    breed: 'Irish Wolf Hound',
    sex: M,
  },
  {
    name: 'Mrs. Clean',
    age: 7,
    color: 'black',
    weight: 59,
    breed: 'Labradoodle',
    sex: F,
  },
  {
    name: 'Sadie',
    age: 5,
    color: 'blue',
    weight: 40,
    breed: 'Weimaraner',
    sex: F,
  },
  {
    name: 'Angus',
    age: 3,
    color: 'brown',
    weight: 54,
    breed: 'Labrador Retriever',
    sex: M,
  },
  {
    name: 'Fergus',
    age: 7,
    color: 'tri-coloured',
    weight: 11,
    breed: 'Chihuahua mix',
    sex: M,
  },
  {
    name: 'Maxy',
    age: 12,
    color: 'tan',
    weight: 33,
    breed: 'Wheaton Terrier',
    sex: F,
  },
  {
    name: 'Tootsie',
    age: 4,
    color: 'red',
    weight: 63,
    breed: 'Rhodesian Ridgeback',
    sex: M,
  },
  {
    name: 'Greta',
    age: 2,
    color: 'white',
    weight: 41,
    breed: 'Australian Cattle Dog',
    sex: F,
  },
  {
    name: 'Stubbs',
    age: 1,
    color: 'Black and white',
    weight: 21,
    breed: 'Jack Russel Terrier',
    sex: M,
  },
  {
    name: 'Atari',
    age: 5,
    color: 'black',
    weight: 43,
    breed: 'Puli',
    sex: F,
  },
  {
    name: 'Flash',
    age: 3,
    color: 'red',
    weight: 119,
    breed: 'Grate Dane',
    sex: M,
  },
  {
    name: 'Libby',
    age: 9,
    color: 'grey',
    weight: 40,
    breed: 'Mix',
    sex: F,
  },
  {
    name: 'Tuppy',
    age: 2,
    color: 'brown',
    weight: 22,
    breed: 'Dachshund',
    sex: M,
  },
  {
    name: 'Tetris',
    age: 7,
    color: 'black and brown',
    weight: 84,
    breed: 'German Shepard',
    sex: M,
  },
  {
    name: 'Zucchi',
    age: 9,
    color: 'white',
    weight: 61,
    breed: 'Grey Hound',
    sex: F,
  },
  {
    name: 'Busta',
    age: 5,
    color: 'red',
    weight: 27,
    breed: 'Cocker Spaniel',
    sex: M,
  },
  {
    name: 'Oreo',
    age: 11,
    color: 'black and white',
    weight: 57,
    breed: 'Dalmatian',
    sex: M,
  },
  {
    name: 'Noodle',
    age: 8,
    color: 'brown, black & white',
    weight: 31,
    breed: 'Potcake',
    sex: F,
  },
  {
    name: 'Bishop',
    age: 7,
    color: 'brown & white',
    weight: 26,
    breed: 'Shetland Sheepdog',
    sex: M,
  },
  {
    name: 'Penny',
    age: 3,
    color: 'white & grey',
    weight: 21,
    breed: 'Whippet',
    sex: F,
  },
  {
    name: 'Monty',
    age: 4,
    color: 'black',
    weight: 35,
    breed: 'Scottish Terrier',
    sex: M,
  },
  {
    name: 'Lancealot',
    age: 18,
    color: 'red & black',
    weight: 45,
    breed: 'Basset Hound',
    sex: M,
  },
  {
    name: 'Sushi',
    age: 4,
    color: 'brown & white',
    weight: 52,
    breed: 'American Bulldog',
    sex: F,
  },
  {
    name: 'Frodo',
    age: 6,
    color: 'red',
    weight: 79,
    breed: 'Mastiff',
    sex: M,
  },
  {
    name: 'Toadstool',
    age: 19,
    color: 'beige',
    weight: 51,
    breed: 'Golden Retriever',
    sex: M,
  },
  {
    name: 'Lenny',
    age: 4,
    color: 'brown & white',
    weight: 48,
    breed: 'English Bulldog',
    sex: M,
  },
  {
    name: 'Isla',
    age: 6,
    color: 'black & brown',
    weight: 31,
    breed: 'Shetland Sheepdog',
    sex: F,
  },
  {
    name: 'Pi',
    age: 8,
    color: 'black',
    weight: 27,
    breed: 'Pug',
    sex: F,
  },
  {
    name: 'Bubbles',
    age: 6,
    color: 'tri coloured',
    weight: 29,
    breed: 'Pembroke Welsh Corgi',
    sex: F,
  },
  {
    name: 'Jet',
    color: 'Black, brown and white',
    age: 10,
    weight: 57,
    breed: 'Beagle Mix',
    sex: M,
  },
  {
    name: 'Mochi',
    color: 'brown & white',
    age: 7,
    weight: 56,
    breed: 'American Bulldog',
    sex: F,
  },

  {
    name: 'Waffle',
    age: 2,
    color: 'blue',
    weight: 79,
    breed: 'Irish Wolf Hound',
    sex: M,
  },
  {
    name: 'Sydney',
    age: 6,
    color: 'black & brown',
    weight: 51,
    breed: 'Labradoodle',
    sex: F,
  },
  {
    name: 'Scarlet',
    age: 4,
    color: 'blue',
    weight: 49,
    breed: 'Weimaraner',
    sex: F,
  },
  {
    name: 'Cowboy',
    age: 4,
    color: 'black',
    weight: 59,
    breed: 'Labrador Retriever',
    sex: M,
  },
  {
    name: 'Pepe',
    age: 6,
    color: 'white',
    weight: 15,
    breed: 'Chihuahua mix',
    sex: M,
  },
  {
    name: 'Ivy',
    age: 10,
    color: 'tan',
    weight: 33,
    breed: 'Wheaton Terrier',
    sex: F,
  },
  {
    name: 'Rolo',
    age: 3,
    color: 'red',
    weight: 73,
    breed: 'Rhodesian Ridgeback',
    sex: M,
  },
  {
    name: 'Betsy',
    age: 1,
    color: 'white & blue',
    weight: 33,
    breed: 'Australian Cattle Dog',
    sex: F,
  },
];
