const basic = [
  {
    name: 'Juno',
    color: 'Black and tan',
    age: 11,
    breed: 'Husky Mix',
    weight: 65,
  },
  {
    name: 'Poppy',
    color: 'Fawn',
    age: 6,
    breed: 'French Bulldog',
    weight: 25,
  },

  {
    name: 'Wuffles',
    age: 12,
    color: 'black',
    weight: 18,
    breed: 'Shih Tzu',
  },
  {
    name: 'Mr. Fusspot',
    age: 9,
    color: 'brown',
    weight: 9,
    breed: 'Toy Poodle',
  },
  {
    name: 'Laddie',
    age: 6,
    color: 'red',
    weight: 40,
    breed: 'Border Collie',
  },
  {
    name: 'Angua',
    age: 4,
    color: 'white',
    weight: 54,
    breed: 'Golden Retriever',
  },
  {
    name: 'Rincewind',
    age: 3,
    color: 'black',
    weight: 8,
    breed: 'Chihuahua',
  },
  {
    name: 'Weatherwax',
    age: 12,
    color: 'brown',
    weight: 13,
    breed: 'Doberman Pinscher',
  },
  {
    name: 'Magrat',
    age: 5,
    color: 'red',
    weight: 60,
    breed: 'Standard Poodle',
  },
  {
    name: 'Greebo',
    age: 2,
    color: 'white',
    weight: 44,
    breed: 'Rottweiler',
  },
  {
    name: 'Stibbons',
    age: 7,
    color: 'black',
    weight: 6,
    breed: 'Yorkshire Terrier',
  },
  {
    name: 'Vetinari',
    age: 5,
    color: 'black',
    weight: 20,
    breed: 'Schipperke',
  },
  {
    name: 'Motzart',
    age: 4,
    color: 'red',
    weight: 135,
    breed: 'Saint Bernard',
  },
  {
    name: 'The Librarian',
    age: 8,
    color: 'red',
    weight: 40,
    breed: 'Basset Hound',
  },
  {
    name: 'TwoFlower',
    age: 3,
    color: 'brown',
    weight: 52,
    breed: 'Chow Chow',
  },
  {
    name: 'Detritus',
    age: 4,
    color: 'white',
    weight: 84,
    breed: 'Mastiff',
  },
  {
    name: 'Carrot',
    age: 10,
    color: 'red',
    weight: 61,
    breed: 'Golden Retriever',
  },
  {
    name: 'Vimes',
    age: 3,
    color: 'brown',
    weight: 38,
    breed: 'English Bulldog',
  },
  {
    name: 'Cherry',
    age: 13,
    color: 'black',
    weight: 51,
    breed: 'Shetland Sheepdog',
  },
  {
    name: 'Nobby',
    age: 9,
    color: 'brown',
    weight: 19,
    breed: 'Pug',
  },
  {
    name: 'Brutha',
    age: 6,
    color: 'white',
    weight: 21,
    breed: 'Pembroke Welsh Corgi',
  },
];
