const dogBreeds = [
  {
    id: 1,
    name: 'Affenpinscher',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 2,
    name: 'Afghan Hound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 3,
    name: 'African Hunting Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 4,
    name: 'Airedale Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 5,
    name: 'Akbash Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 6,
    name: 'Akita',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 7,
    name: 'Alapaha Blue Blood Bulldog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 8,
    name: 'Alaskan Husky',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 9,
    name: 'Alaskan Malamute',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 10,
    name: 'American Bulldog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 11,
    name: 'American Bully',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 12,
    name: 'American Eskimo Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 13,
    name: 'American Eskimo Dog (Miniature)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 14,
    name: 'American Foxhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 15,
    name: 'American Pit Bull Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 16,
    name: 'American Staffordshire Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 17,
    name: 'American Water Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 18,
    name: 'Anatolian Shepherd Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 19,
    name: 'Appenzeller Sennenhund',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 21,
    name: 'Australian Cattle Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 22,
    name: 'Australian Kelpie',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 23,
    name: 'Australian Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 24,
    name: 'Australian Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 25,
    name: 'Azawakh',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 26,
    name: 'Barbet',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 28,
    name: 'Basenji',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 29,
    name: 'Basset Bleu de Gascogne',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 30,
    name: 'Basset Hound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 31,
    name: 'Beagle',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 32,
    name: 'Bearded Collie',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 33,
    name: 'Beauceron',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 34,
    name: 'Bedlington Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 36,
    name: 'Belgian Malinois',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 38,
    name: 'Belgian Tervuren',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 41,
    name: 'Bernese Mountain Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 42,
    name: 'Bichon Frise',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 43,
    name: 'Black and Tan Coonhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 45,
    name: 'Bloodhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 47,
    name: 'Bluetick Coonhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 48,
    name: 'Boerboel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 50,
    name: 'Border Collie',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 51,
    name: 'Border Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 53,
    name: 'Boston Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 54,
    name: 'Bouvier des Flandres',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 55,
    name: 'Boxer',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 56,
    name: 'Boykin Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 57,
    name: 'Bracco Italiano',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 58,
    name: 'Briard',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 59,
    name: 'Brittany',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 61,
    name: 'Bull Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 62,
    name: 'Bull Terrier (Miniature)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 64,
    name: 'Bullmastiff',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 65,
    name: 'Cairn Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 67,
    name: 'Cane Corso',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 68,
    name: 'Cardigan Welsh Corgi',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 69,
    name: 'Catahoula Leopard Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 70,
    name: 'Caucasian Shepherd (Ovcharka)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 71,
    name: 'Cavalier King Charles Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 76,
    name: 'Chesapeake Bay Retriever',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 78,
    name: 'Chinese Crested',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 79,
    name: 'Chinese Shar-Pei',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 80,
    name: 'Chinook',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 81,
    name: 'Chow Chow',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 84,
    name: 'Clumber Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 86,
    name: 'Cocker Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 87,
    name: 'Cocker Spaniel (American)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 89,
    name: 'Coton de Tulear',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 92,
    name: 'Dalmatian',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 94,
    name: 'Doberman Pinscher',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 95,
    name: 'Dogo Argentino',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 98,
    name: 'Dutch Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 101,
    name: 'English Setter',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 102,
    name: 'English Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 103,
    name: 'English Springer Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 104,
    name: 'English Toy Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 105,
    name: 'English Toy Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 107,
    name: 'Eurasier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 108,
    name: 'Field Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 110,
    name: 'Finnish Lapphund',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 111,
    name: 'Finnish Spitz',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 113,
    name: 'French Bulldog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 114,
    name: 'German Pinscher',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 115,
    name: 'German Shepherd Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 116,
    name: 'German Shorthaired Pointer',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 119,
    name: 'Giant Schnauzer',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 120,
    name: 'Glen of Imaal Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 121,
    name: 'Golden Retriever',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 123,
    name: 'Gordon Setter',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 124,
    name: 'Great Dane',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 125,
    name: 'Great Pyrenees',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 127,
    name: 'Greyhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 128,
    name: 'Griffon Bruxellois',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 129,
    name: 'Harrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 130,
    name: 'Havanese',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 134,
    name: 'Irish Setter',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 135,
    name: 'Irish Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 137,
    name: 'Irish Wolfhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 138,
    name: 'Italian Greyhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 140,
    name: 'Japanese Chin',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 141,
    name: 'Japanese Spitz',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 142,
    name: 'Keeshond',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 144,
    name: 'Komondor',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 145,
    name: 'Kooikerhondje',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 147,
    name: 'Kuvasz',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 149,
    name: 'Labrador Retriever',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 151,
    name: 'Lagotto Romagnolo',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 153,
    name: 'Lancashire Heeler',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 155,
    name: 'Leonberger',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 156,
    name: 'Lhasa Apso',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 161,
    name: 'Maltese',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 165,
    name: 'Miniature American Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 167,
    name: 'Miniature Pinscher',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 168,
    name: 'Miniature Schnauzer',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 171,
    name: 'Newfoundland',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 172,
    name: 'Norfolk Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 176,
    name: 'Norwich Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 177,
    name: 'Nova Scotia Duck Tolling Retriever',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 178,
    name: 'Old English Sheepdog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 179,
    name: 'Olde English Bulldogge',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 181,
    name: 'Papillon',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 183,
    name: 'Pekingese',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 184,
    name: 'Pembroke Welsh Corgi',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 185,
    name: 'Perro de Presa Canario',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 188,
    name: 'Pharaoh Hound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 189,
    name: 'Plott',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 193,
    name: 'Pomeranian',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 196,
    name: 'Poodle (Miniature)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 197,
    name: 'Poodle (Toy)',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 201,
    name: 'Pug',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 204,
    name: 'Puli',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 205,
    name: 'Pumi',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 207,
    name: 'Rat Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 208,
    name: 'Redbone Coonhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 209,
    name: 'Rhodesian Ridgeback',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 210,
    name: 'Rottweiler',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 211,
    name: 'Russian Toy',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 212,
    name: 'Saint Bernard',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 213,
    name: 'Saluki',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 214,
    name: 'Samoyed',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 216,
    name: 'Schipperke',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 218,
    name: 'Scottish Deerhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 219,
    name: 'Scottish Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 221,
    name: 'Shetland Sheepdog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 222,
    name: 'Shiba Inu',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 223,
    name: 'Shih Tzu',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 225,
    name: 'Shiloh Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 226,
    name: 'Siberian Husky',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 228,
    name: 'Silky Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 232,
    name: 'Smooth Fox Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 233,
    name: 'Soft Coated Wheaten Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 235,
    name: 'Spanish Water Dog',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 236,
    name: 'Spinone Italiano',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 238,
    name: 'Staffordshire Bull Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 239,
    name: 'Standard Schnauzer',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 242,
    name: 'Swedish Vallhund',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 243,
    name: 'Thai Ridgeback',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 244,
    name: 'Tibetan Mastiff',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 245,
    name: 'Tibetan Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 246,
    name: 'Tibetan Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 248,
    name: 'Toy Fox Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 250,
    name: 'Treeing Walker Coonhound',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 251,
    name: 'Vizsla',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 253,
    name: 'Weimaraner',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 254,
    name: 'Welsh Springer Spaniel',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 256,
    name: 'West Highland White Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 257,
    name: 'Whippet',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 258,
    name: 'White Shepherd',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 259,
    name: 'Wire Fox Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 260,
    name: 'Wirehaired Pointing Griffon',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 261,
    name: 'Wirehaired Vizsla',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 262,
    name: 'Xoloitzcuintli',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
  {
    id: 264,
    name: 'Yorkshire Terrier',
    origin: '',
    type: '',
    body: '',
    coat: '',
    coat_pattern: '',
  },
];

// var listHolder = document.getElementById("list");

// var innerBreeds = "";

// breeds.map(function(breed){
//   innerBreeds += "<p>" + breed.id  + " - " + breed.name  + "</p>";
// });

// listHolder.innerHTML = innerBreeds;
