const basic = [
  {
    name: 'Juno',
    color: 'Black and tan',
    age: 11.5,
    breed: 'Husky Mix',
    weight: 65,
  },
  {
    name: 'Poppy',
    color: 'Fawn',
    age: 6,
    breed: 'French Bulldog',
    weight: 25,
  },

  {
    name: 'Wuffles',
    age: ,
    color: 'black',
    size: 8,
    breed: 'Shih Tzu',
  },
  {
    name: 'Mr. Fusspot',
    age: ,
    color: 'brown',
    size: 24,
    breed: 'Toy Poodle',
  },
  {
    name: 'Laddie',
    age: ,
    color: 'red',
    size: 30,
    breed: 'Border Collie',
  },
  {
    name: 'Angua',
    age: ,
    color: 'white',
    size: 34,
    breed: 'Golden Retriever',
  },
  {
    name: 'Rincewind',
    age: ,
    color: 'black',
    size: 18,
    breed: 'Chihuahua',
  },
  {
    name: 'Weatherwax',
    age: ,
    color: 'brown',
    size: 13,
    breed: 'Doberman Pinscher',
  },
  {
    name: 'Magrat',
    age: ,
    color: 'red',
    size: 30,
    breed: 'Standard Poodle',
  },
  {
    name: 'Greebo',
    age: ,
    color: 'white',
    size: 44,
    breed: 'Rottweiler',
  },
  {
    name: 'Stibbons',
    age: ,
    color: 'black',
    size: 6,
    breed: 'Yorkshire Terrier',
  },
  {
    name: 'Vetinari',
    age: ,
    color: 'black',
    size: 20,
    breed: 'Schipperke',
  },
  {
    age: ,
    color: 'red',
    size: 35,
    breed: 'Saint Bernard',
  },
  {
    name: 'The Librarian',
    age: ,
    color: 'red',
    size: 40,
    breed: 'Basset Hound',
  },
  {
    name: 'TwoFlower',
    age: ,
    color: 'brown',
    size: 12,
    breed: 'Chow Chow',
  },
  {
    name: 'Detritus',
    age: ,
    color: 'white',
    size: 44,
    breed: 'Mastiff',
  },
  {
    name: 'Carrot',
    age: ,
    color: 'red',
    size: 31,
    breed: 'Golden Retriever',
  },
  {
    name: 'Vimes',
    age: ,
    color: 'brown',
    size: 28,
    breed: 'English Bulldog',
  },
  {
    name: 'Cherry',
    age: ,
    color: 'black',
    size: 11,
    breed: 'Shetland Sheepdog',
  },
  {
    name: 'Nobby',
    age: ,
    color: 'brown',
    size: 9,
    breed: 'Pug',
  },
  {
    name: 'Brutha',
    age: ,
    color: 'white',
    size: 21,
    breed: 'Pembroke Welsh Corgi',
  },
];
