// structure:
// {
//   name: 'string',
//   age: number,
//   color: 'string',
//   weight: number,
//   breed: 'string',
//   sex: 'string',
//   photo: 'string', - https://unsplash.com/
// },

const dogs = [
  {
    name: "Juno",
    age: 11,
    color: "black & tan",
    weight: 65,
    breed: "Husky Mix",
    sex: "F",
    photo: "",
  },
  {
    name: "Poppy",
    age: 6,
    color: "fawn",
    weight: 25,
    breed: "French Bulldog",
    sex: "F",
    photo: "",
  },

  {
    name: "Wuffles",
    age: 12,
    color: "black",
    weight: 18,
    breed: "Shih Tzu",
    sex: "M",
    photo: "",
  },
  {
    name: "Mr. Fusspot",
    age: 9,
    color: "brown",
    weight: 9,
    breed: "Toy Poodle",
    sex: "M",
    photo: "",
  },
  {
    name: "Laddie",
    age: 6,
    color: "red",
    weight: 40,
    breed: "Border Collie",
    sex: "M",
    photo: "",
  },
  {
    name: "Agusta",
    age: 4,
    color: "white",
    weight: 54,
    breed: "Golden Retriever",
    sex: "F",
    photo: "",
  },
  {
    name: "Rincewind",
    age: 3,
    color: "black",
    weight: 8,
    breed: "Chihuahua",
    sex: "M",
    photo: "",
  },
  {
    name: "Weatherwax",
    age: 12,
    color: "brown",
    weight: 13,
    breed: "Doberman Pinscher",
    sex: "M",
    photo: "",
  },
  {
    name: "Magrat",
    age: 5,
    color: "red",
    weight: 60,
    breed: "Standard Poodle",
    sex: "F",
    photo: "",
  },
  {
    name: "Greebo",
    age: 2,
    color: "black",
    weight: 44,
    breed: "Rottweiler",
    sex: "M",
    photo: "",
  },
  {
    name: "Stibbons",
    age: 7,
    color: "black",
    weight: 6,
    breed: "Yorkshire Terrier",
    sex: "F",
    photo: "",
  },
  {
    name: "Vetinari",
    age: 5,
    color: "black",
    weight: 20,
    breed: "Schipperke",
    sex: "M",
    photo: "",
  },
  {
    name: "Motzart",
    age: 4,
    color: "red",
    weight: 135,
    breed: "Saint Bernard",
    sex: "M",
    photo: "",
  },
  {
    name: "The Librarian",
    age: 8,
    color: "red",
    weight: 40,
    breed: "Basset Hound",
    sex: "F",
    photo: "",
  },
  {
    name: "TwoFlower",
    age: 3,
    color: "brown",
    weight: 52,
    breed: "Chow Chow",
    sex: "F",
    photo: "",
  },
  {
    name: "Detritus",
    age: 4,
    color: "white",
    weight: 84,
    breed: "Mastiff",
    sex: "M",
    photo: "",
  },
  {
    name: "Carrot",
    age: 10,
    color: "red",
    weight: 61,
    breed: "Golden Retriever",
    sex: "F",
    photo: "",
  },
  {
    name: "Vimes",
    age: 3,
    color: "brown",
    weight: 38,
    breed: "English Bulldog",
    sex: "M",
    photo: "",
  },
  {
    name: "Cherry",
    age: 13,
    color: "brown",
    weight: 31,
    breed: "Shetland Sheepdog",
    sex: "F",
    photo: "",
  },
  {
    name: "Nobby",
    age: 9,
    color: "fawn",
    weight: 19,
    breed: "Pug",
    sex: "M",
    photo: "",
  },
  {
    name: "Brutha",
    age: 6,
    color: "white & tan",
    weight: 21,
    breed: "Pembroke Welsh Corgi",
    sex: "M",
    photo: "/assets/pet-images/ivana-la-tycZhR54Ddk-unsplash.jpg",
  },
  {
    name: "Puddles",
    color: "Black and white",
    age: 11,
    weight: 65,
    breed: "Beagle Mix",
    sex: "F",
    photo: "",
  },
  {
    name: "Sandy",
    color: "tan",
    age: 6,
    weight: 69,
    breed: "American Bulldog",
    sex: "F",
    photo: "",
  },

  {
    name: "Fluffles",
    age: 1,
    color: "grey",
    weight: 88,
    breed: "Irish Wolf Hound",
    sex: "M",
    photo: "",
  },
  {
    name: "Mrs. Clean",
    age: 7,
    color: "black",
    weight: 59,
    breed: "Labradoodle",
    sex: "F",
    photo: "",
  },
  {
    name: "Sadie",
    age: 5,
    color: "blue",
    weight: 40,
    breed: "Weimaraner",
    sex: "F",
    photo: "",
  },
  {
    name: "Angus",
    age: 3,
    color: "brown",
    weight: 54,
    breed: "Labrador Retriever",
    sex: "M",
    photo: "/assets/pet-images/lucrezia-carnelos-0liYTl4dJxk-unsplash.jpg",
  },
  {
    name: "Fergus",
    age: 7,
    color: "tri-coloured",
    weight: 11,
    breed: "Chihuahua mix",
    sex: "M",
    photo: "",
  },
  {
    name: "Maxy",
    age: 12,
    color: "tan",
    weight: 33,
    breed: "Wheaton Terrier",
    sex: "F",
    photo: "",
  },
  {
    name: "Tootsie",
    age: 4,
    color: "red",
    weight: 63,
    breed: "Rhodesian Ridgeback",
    sex: "M",
    photo: "",
  },
  {
    name: "Greta",
    age: 2,
    color: "white",
    weight: 41,
    breed: "Australian Cattle Dog",
    sex: "F",
    photo: "",
  },
  {
    name: "Stubbs",
    age: 1,
    color: "Black and white",
    weight: 21,
    breed: "Jack Russel Terrier",
    sex: "M",
    photo: "",
  },
  {
    name: "Atari",
    age: 5,
    color: "black",
    weight: 43,
    breed: "Puli",
    sex: "F",
    photo: "",
  },
  {
    name: "Flash",
    age: 3,
    color: "red",
    weight: 119,
    breed: "Grate Dane",
    sex: "M",
    photo: "",
  },
  {
    name: "Libby",
    age: 9,
    color: "grey",
    weight: 40,
    breed: "Mix",
    sex: "F",
    photo: "",
  },
  {
    name: "Tuppy",
    age: 2,
    color: "brown",
    weight: 22,
    breed: "Dachshund",
    sex: "M",
    photo: "",
  },
  {
    name: "Tetris",
    age: 7,
    color: "black and brown",
    weight: 84,
    breed: "German Shepard",
    sex: "M",
    photo: "assets/pet-images/michael-dziedzic-si06cFB0g1s-unsplash (1).jpg",
  },
  {
    name: "Zucchi",
    age: 9,
    color: "white",
    weight: 61,
    breed: "Grey Hound",
    sex: "F",
    photo: "",
  },
  {
    name: "Busta",
    age: 5,
    color: "red",
    weight: 27,
    breed: "Cocker Spaniel",
    sex: "M",
    photo: "",
  },
  {
    name: "Oreo",
    age: 11,
    color: "black and white",
    weight: 57,
    breed: "Dalmatian",
    sex: "M",
    photo: "",
  },
  {
    name: "Noodle",
    age: 8,
    color: "brown, black & white",
    weight: 31,
    breed: "Potcake",
    sex: "F",
    photo: "",
  },
  {
    name: "Bishop",
    age: 7,
    color: "brown & white",
    weight: 26,
    breed: "Shetland Sheepdog",
    sex: "M",
    photo: "",
  },
  {
    name: "Penny",
    age: 3,
    color: "white & grey",
    weight: 21,
    breed: "Whippet",
    sex: "F",
    photo: "",
  },
  {
    name: "Monty",
    age: 4,
    color: "black",
    weight: 35,
    breed: "Scottish Terrier",
    sex: "M",
    photo: "",
  },
  {
    name: "Lancealot",
    age: 18,
    color: "red & black",
    weight: 45,
    breed: "Basset Hound",
    sex: "M",
    photo: "",
  },
  {
    name: "Sushi",
    age: 4,
    color: "brown & white",
    weight: 52,
    breed: "American Bulldog",
    sex: "F",
    photo: "",
  },
  {
    name: "Frodo",
    age: 6,
    color: "red",
    weight: 79,
    breed: "Mastiff",
    sex: "M",
    photo: "",
  },
  {
    name: "Toadstool",
    age: 19,
    color: "beige",
    weight: 51,
    breed: "Golden Retriever",
    sex: "M",
    photo: "",
  },
  {
    name: "Lenny",
    age: 4,
    color: "brown & white",
    weight: 48,
    breed: "English Bulldog",
    sex: "M",
    photo: "",
  },
  {
    name: "Isla",
    age: 6,
    color: "black & brown",
    weight: 31,
    breed: "Shetland Sheepdog",
    sex: "F",
    photo: "",
  },
  {
    name: "Pi",
    age: 8,
    color: "black",
    weight: 27,
    breed: "Pug",
    sex: "F",
    photo: "/assets/pet-images/Pi-black-pug1.jpg",
  },
  {
    name: "Bubbles",
    age: 6,
    color: "tri coloured",
    weight: 29,
    breed: "Pembroke Welsh Corgi",
    sex: "F",
    photo: "",
  },
  {
    name: "Jet",
    color: "Black, brown and white",
    age: 10,
    weight: 57,
    breed: "Beagle",
    sex: "M",
    photo: "/assets/pet-images/luke-macgillivray-p_qco2Eo-E0-unsplash.jpg",
  },
  {
    name: "Mochi",
    color: "brown & white",
    age: 7,
    weight: 56,
    breed: "American Bulldog",
    sex: "F",
    photo: "",
  },

  {
    name: "Waffle",
    age: 2,
    color: "blue",
    weight: 79,
    breed: "Irish Wolf Hound",
    sex: "M",
    photo: "",
  },
  {
    name: "Sydney",
    age: 6,
    color: "black & brown",
    weight: 51,
    breed: "Labradoodle",
    sex: "F",
    photo: "",
  },
  {
    name: "Scarlet",
    age: 4,
    color: "blue",
    weight: 49,
    breed: "Weimaraner",
    sex: "F",
    photo: "",
  },
  {
    name: "Cowboy",
    age: 4,
    color: "black",
    weight: 59,
    breed: "Labrador Retriever",
    sex: "M",
    photo: "",
  },
  {
    name: "Pepe",
    age: 6,
    color: "white",
    weight: 15,
    breed: "Chihuahua mix",
    sex: "M",
    photo: "",
  },
  {
    name: "Ivy",
    age: 10,
    color: "tan",
    weight: 35,
    breed: "Wheaton Terrier",
    sex: "F",
    photo: "",
  },
  {
    name: "Rolo",
    age: 3,
    color: "red",
    weight: 73,
    breed: "Rhodesian Ridgeback",
    sex: "M",
    photo: "",
  },
  {
    name: "Betsy",
    age: 1,
    color: "white & blue",
    weight: 33,
    breed: "Australian Cattle Dog",
    sex: "F",
    photo: "",
  },
  {
    name: "Jester",
    age: 1,
    color: "black & brown",
    weight: 69,
    breed: "Rottweiler",
    sex: "M",
    photo: "",
  },
  {
    name: "Kira",
    age: 11,
    color: "tan & white",
    weight: 42,
    breed: "Bulldog Mix",
    sex: "F",
    photo: "",
  },
  {
    name: "Ducky",
    age: 8,
    color: "beige",
    weight: 14,
    breed: "Shih Tzu",
    sex: "F",
    photo: "",
  },
  {
    name: "Stella",
    age: 6,
    color: "white & brindle",
    weight: 65,
    breed: "Boxer",
    sex: "F",
    photo: "",
  },
  {
    name: "Rocky",
    age: 3,
    color: "brindle",
    weight: 72,
    breed: "Boxer",
    sex: "M",
    photo: "",
  },
  {
    name: "Birdie",
    age: 1,
    color: "beige",
    weight: 12,
    breed: "Pomeranian",
    sex: "F",
    photo: "",
  },
  {
    name: "Georgia",
    age: 7,
    color: "beige & black",
    weight: 65,
    breed: "Doberman mix",
    sex: "F",
    photo: "",
  },

  {
    name: "May",
    age: 9,
    color: "silver",
    weight: 142,
    breed: "Great Dane",
    sex: "F",
    photo: "",
  },

  {
    name: "Pongo",
    age: 7,
    color: "white & black",
    weight: 101,
    breed: "Dalmatian",
    sex: "M",
    pohot: "",
  },
];

//https://dogoftheday.com/
